# Usa la imagen base de Python 3.9.6
FROM python:3.9.6

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Comando para iniciar la aplicación de Cocina
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]